### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by andypiper** [ckolderup/postmarks#139]
I’d like to propose that the project adopt a code of conduct around participation and interactions. A straightforward and (in my view) appropriate existing text to adopt would be the [Contributor Covenant](https://www.contributor-covenant.org/); by all means, other options are available.

As a contributor and lead on other projects, I can say from experience that I feel that this would help to set expectations for future interactions. I’ve only seen excellent behaviours and collaboration around Postmarks to date, and putting this in place can help to keep that vibe healthy.

Finally, lest this be seen as an overhead, I would also be willing to offer my support as a point of contact for any reports or investigations that may (hopefully not!) be required in the future.

Just looking for direction here - happy to add the relevant file to this repo directly once a choice of guidelines is agreed 🤗

**Comment by ckolderup** [comment]
Thank you, Andy! This is part of why I've been putting off #68 until I can get a bit more focus (this coming week, hopefully), because I was mentally packaging up a CoC as part of that, but calling it out explicitly is very warranted.

I agree that we've been off to a very fortunate start on this project but that we shouldn't take it for granted and your pedigree should hopefully be reassuring as an alternate contact option if people feel it's necessary. Figuring out governance-wise what any consequences should be introduces some complications, I would assume, considering the temporary "benevolent dictator"-type role I find myself in... but presumably that's well-worn territory in OSS?

**Comment by andypiper** [comment]
I think the only thing we need to identify is how to report potential violations, per the directions on how to adopt the Contributor Covenant:

> You must add a contact method to the placeholder in the document so that people know how to report violations.
