### ISSUE TITLE
tag search incorrectly selects part of words

### ISSUE THREAD

**Issue by ajft** [ckolderup/postmarks#177]
Tag filters, eg https://pear-voracious-lemonade.glitch.me/tagged/ebook displays items that are both tagged "#ebook" and "#facebook"

**Comment by ckolderup** [comment]
thanks! Definitely not working as intended; I'll try to take a look soon.

**Comment by TomCasavant** [comment]
If I'm not mistaken that's the same issue described in #152

When did you last update your code?

**Comment by ckolderup** [comment]
good spot-- I took a look at the Glitch project in its editor and it does appear to be somewhat out-of-date. @ajft, please get the code up to date in your container-- you can try following [the instructions I posted a while back](https://github.com/ckolderup/postmarks/issues/156#issuecomment-1767357398), though I recommend backing up the project somehow beforehand since we haven't fully verified it yet. You may also run into merge conflicts involving any CSS/layout customizations you've made.
