### ISSUE TITLE
Default avatar in account.json.example is an invalid url

### ISSUE THREAD

**Issue by benbrown** [ckolderup/postmarks#52]
It is set to this:
https://cdn.glitch.global/8eaf209c-2fa9-4353-9b99-e8d8f3a5f8d4/postmarks-logo-white-small.png?v=1693610556689

Doesn't seem valid.

**Comment by benbrown** [comment]
Huh! Weird, maybe my ad blocker is blocking it.

**Comment by ckolderup** [comment]
Gonna go ahead and close this since I haven't seen any other reports and I assume it has to do with the handful of upstream things I've heard about cdn.glitch.global URLs. I could also theoretically refer to the image in the statically-served public directory, but I want to limit the number of requests in the container when it's being hosted on Glitch (and I'd like people to use their own avatar anyway!)
