### ISSUE TITLE
enhance tag filter view to do tag intersection

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#55]
/tagged/music/youtube would show just bookmarks that are music + youtube

**Comment by ckolderup** [comment]
@j12i@weirder.earth (who reached out about this in the first place) pointed out on Mastodon that we may want some way to do tag unions as well, in which case we may want to consider the URL schema that would support both.

Looking at other bookmarking sites (or even just things that have tags + good URL hygiene) may be informative here.

**Comment by steve-bate** [comment]
I added experimental support for tag intersection on [my instance](https://bookmarks.stevebate.dev). If you go to one of the tag views, you'll see a "+" next to the tags. Clicking the "+" will add the tag to the query/view. When there are multiple tags selected, the selected tags will have a "-" next to them, and nonselected tags will have a "+". For a single tag view, the current tag will be disabled with no "+/-" control next to it. I'm not claiming this is the optimal UX (I'm more of a backend developer), but it seems to work reasonably well.

I didn't try to implement tag unions because I can't think of a personal use case for them.

**Comment by ckolderup** [comment]
It's looking good to me! I don't think there's a strong need to do unions right now (only context you'll hear me say that). If you have the time, are you cool with setting up a PR for it?

**Comment by ckolderup** [comment]
Closed by #96, thanks again!
